/// Generated by AssetsRefGenerator on 2020/08/03
class Res {
  static const String app_icon = "assets/app_icon/app_icon.png";
  static const String OFL = "assets/fonts/Poppins/OFL.txt";
  static const String app_icon_vector = "assets/vector/app_icon_vector.svg";
  static const String debt = "assets/vector/debt.svg";
  static const String debt_unselected = "assets/vector/debt_unselected.svg";
  static const String Facebook = "assets/vector/Facebook.svg";
  static const String Google = "assets/vector/Google.svg";
  static const String transaction = "assets/vector/transaction.svg";
  static const String transaction_unselected = "assets/vector/transaction_unselected.svg";
}
